# personal profile

_dotfiles_load_runtime_env() {
  # Preferred path: encrypted runtime env generated by bootstrap.
  if [ -f "$HOME/.env.local.sops" ] && command -v sops >/dev/null 2>&1; then
    _dotfiles_env_tmp="$(mktemp)" || return
    if sops -d "$HOME/.env.local.sops" > "$_dotfiles_env_tmp" 2>/dev/null; then
      set -a
      # shellcheck disable=SC1090
      . "$_dotfiles_env_tmp"
      set +a
    fi
    rm -f "$_dotfiles_env_tmp"
  elif [ -f "$HOME/.env.local" ]; then
    # Legacy fallback for previous bootstrap versions.
    # shellcheck disable=SC1090
    . "$HOME/.env.local"
  fi

  [ -z "${GH_TOKEN:-}" ] && [ -n "${GITHUB_TOKEN:-}" ] && export GH_TOKEN="$GITHUB_TOKEN"
}

_dotfiles_load_runtime_env
export DOTFILES_RUNTIME_ENV_LOADED=1

# Prefer 1Password SSH agent socket when available in WSL/Linux.
[ -S /tmp/1password-agent.sock ] && export SSH_AUTH_SOCK=/tmp/1password-agent.sock

[ -n "$BASH" ] && [ -f ~/.bashrc ] && . ~/.bashrc

# uv
export PATH="$HOME/.local/bin:$PATH"

{ ble-edit/exec:gexec/.save-lastarg; } &>/dev/null
