# personal profile

# Ensure Homebrew commands are available in non-interactive login shells too.
[ -f "/home/linuxbrew/.linuxbrew/bin/brew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
DOTFILES_RUNTIME_ENV_FILE="${DOTFILES_RUNTIME_ENV_FILE:-$HOME/.config/dotfiles/runtime.env}"
[ -f "$DOTFILES_RUNTIME_ENV_FILE" ] && . "$DOTFILES_RUNTIME_ENV_FILE"

_dotfiles_load_runtime_env() {
  # Fallback for legacy setups that persisted SOPS key in ~/.profile.
  if [ -z "${SOPS_AGE_KEY:-}" ] && [ -f "$HOME/.profile" ]; then
    _dotfiles_sops_key="$(awk -F'\"' '/^export SOPS_AGE_KEY=/{print $2}' "$HOME/.profile" | tail -n1 | tr -d '\r')"
    [ -n "$_dotfiles_sops_key" ] && export SOPS_AGE_KEY="$_dotfiles_sops_key"
  fi
  if [ -z "${SOPS_AGE_KEY_FILE:-}" ] && [ -f "$HOME/.profile" ]; then
    _dotfiles_sops_key_file="$(awk -F'\"' '/^export SOPS_AGE_KEY_FILE=/{print $2}' "$HOME/.profile" | tail -n1 | tr -d '\r')"
    [ -n "$_dotfiles_sops_key_file" ] && export SOPS_AGE_KEY_FILE="$_dotfiles_sops_key_file"
  fi

  # Preferred path: encrypted runtime env generated by bootstrap.
  if [ -f "$HOME/.env.local.sops" ] && command -v sops >/dev/null 2>&1; then
    _dotfiles_env_tmp="$(mktemp)" || return
    if sops -d "$HOME/.env.local.sops" > "$_dotfiles_env_tmp" 2>/dev/null; then
      set -a
      # shellcheck disable=SC1090
      . "$_dotfiles_env_tmp"
      set +a
    fi
    rm -f "$_dotfiles_env_tmp"
  elif [ -f "$HOME/.env.local" ]; then
    # Legacy fallback for previous bootstrap versions.
    # shellcheck disable=SC1090
    . "$HOME/.env.local"
  fi

  [ -z "${GH_TOKEN:-}" ] && [ -n "${GITHUB_TOKEN:-}" ] && export GH_TOKEN="$GITHUB_TOKEN"
  [ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] && export OP_SERVICE_ACCOUNT_TOKEN="$(printf '%s' "$OP_SERVICE_ACCOUNT_TOKEN" | tr -d '\r')"
  [ -n "${GH_TOKEN:-}" ] && export GH_TOKEN="$(printf '%s' "$GH_TOKEN" | tr -d '\r')"
  [ -n "${GITHUB_TOKEN:-}" ] && export GITHUB_TOKEN="$(printf '%s' "$GITHUB_TOKEN" | tr -d '\r')"
  [ -n "${SOPS_AGE_KEY:-}" ] && export SOPS_AGE_KEY="$(printf '%s' "$SOPS_AGE_KEY" | tr -d '\r')"
  [ -n "${SOPS_AGE_KEY_FILE:-}" ] && export SOPS_AGE_KEY_FILE="$(printf '%s' "$SOPS_AGE_KEY_FILE" | tr -d '\r')"
}

_dotfiles_load_runtime_env
export DOTFILES_RUNTIME_ENV_LOADED=1

# Keep a stable signer command name in WSL/Linux.
_dotfiles_ensure_op_ssh_sign() {
  if command -v op-ssh-sign >/dev/null 2>&1; then
    return
  fi
  if ! command -v op-ssh-sign-wsl.exe >/dev/null 2>&1; then
    return
  fi

  mkdir -p "$HOME/.local/bin"
  cat > "$HOME/.local/bin/op-ssh-sign" <<'EOF'
#!/usr/bin/env bash
exec op-ssh-sign-wsl.exe "$@"
EOF
  chmod 700 "$HOME/.local/bin/op-ssh-sign"
}

_dotfiles_ensure_op_ssh_sign


# Prefer 1Password SSH agent socket when available in WSL/Linux.
[ -S /tmp/1password-agent.sock ] && export SSH_AUTH_SOCK=/tmp/1password-agent.sock

[ -n "$BASH" ] && [ -f ~/.bashrc ] && . ~/.bashrc

# uv
export PATH="$HOME/.local/bin:$PATH"

{ ble-edit/exec:gexec/.save-lastarg; } &>/dev/null
