# personal profile

_dotfiles_load_runtime_env() {
  # For non-interactive login shells, recover persisted age env from this file.
  if [ -z "${SOPS_AGE_KEY:-}" ] && [ -f "$HOME/.profile" ]; then
    _dotfiles_sops_key="$(sed -n 's/^export SOPS_AGE_KEY=\"\(.*\)\"$/\1/p' "$HOME/.profile" | tail -n1)"
    [ -n "$_dotfiles_sops_key" ] && export SOPS_AGE_KEY="$_dotfiles_sops_key"
  fi
  if [ -z "${SOPS_AGE_KEY_FILE:-}" ] && [ -f "$HOME/.profile" ]; then
    _dotfiles_sops_key_file="$(sed -n 's/^export SOPS_AGE_KEY_FILE=\"\(.*\)\"$/\1/p' "$HOME/.profile" | tail -n1)"
    [ -n "$_dotfiles_sops_key_file" ] && export SOPS_AGE_KEY_FILE="$_dotfiles_sops_key_file"
  fi

  # Preferred path: encrypted runtime env generated by bootstrap.
  if [ -f "$HOME/.env.local.sops" ] && command -v sops >/dev/null 2>&1; then
    _dotfiles_env_tmp="$(mktemp)" || return
    if sops -d "$HOME/.env.local.sops" > "$_dotfiles_env_tmp" 2>/dev/null; then
      set -a
      # shellcheck disable=SC1090
      . "$_dotfiles_env_tmp"
      set +a
    fi
    rm -f "$_dotfiles_env_tmp"
  elif [ -f "$HOME/.env.local" ]; then
    # Legacy fallback for previous bootstrap versions.
    # shellcheck disable=SC1090
    . "$HOME/.env.local"
  fi

  [ -z "${GH_TOKEN:-}" ] && [ -n "${GITHUB_TOKEN:-}" ] && export GH_TOKEN="$GITHUB_TOKEN"
}

_dotfiles_load_runtime_env
export DOTFILES_RUNTIME_ENV_LOADED=1

# Keep a stable signer command name in WSL/Linux.
_dotfiles_ensure_op_ssh_sign() {
  if command -v op-ssh-sign >/dev/null 2>&1; then
    return
  fi
  if ! command -v op-ssh-sign-wsl.exe >/dev/null 2>&1; then
    return
  fi

  mkdir -p "$HOME/.local/bin"
  cat > "$HOME/.local/bin/op-ssh-sign" <<'EOF'
#!/usr/bin/env bash
exec op-ssh-sign-wsl.exe "$@"
EOF
  chmod 700 "$HOME/.local/bin/op-ssh-sign"
}

_dotfiles_ensure_op_ssh_sign

# Prefer 1Password SSH agent socket when available in WSL/Linux.
[ -S /tmp/1password-agent.sock ] && export SSH_AUTH_SOCK=/tmp/1password-agent.sock

[ -n "$BASH" ] && [ -f ~/.bashrc ] && . ~/.bashrc

# uv
export PATH="$HOME/.local/bin:$PATH"

{ ble-edit/exec:gexec/.save-lastarg; } &>/dev/null
