################################################################################
# app/df/powershell/profile.ps1
#
# Main PowerShell profile entrypoint for this dotfiles repository.
# Responsibilities:
# - Load helper functions and runtime secrets.
# - Load environment, checks, plugins, aliases, completions, and WSL bridge.
# - Keep startup deterministic across fresh bootstrap and daily terminal usage.
################################################################################

#set default directory
#Set-Location d:\projects


#skip env-check
Set-ItemProperty -Path HKCU:\Environment -Name 'PWSH_SKIP_ENV_CHECK' -Value "$Env:USERPROFILE\clients"

#run profile modules
$PWSconfDir = $PSScriptRoot

. $PWSconfDir\_functions.ps1	-WarningAction SilentlyContinue

# load runtime secrets from encrypted env file generated by bootstrap
$envLocalSopsPath = Join-Path $Env:USERPROFILE '.env.local.sops'
$envLocalPlainPath = Join-Path $Env:USERPROFILE '.env.local'
if (Test-Path -Path $envLocalSopsPath -PathType Leaf) {
	Import-DotEnvFromSops -EncryptedPath $envLocalSopsPath | Out-Null
}
elseif (Test-Path -Path $envLocalPlainPath -PathType Leaf) {
	# Legacy fallback for older bootstrap versions.
	Import-DotEnvFile -Path $envLocalPlainPath | Out-Null
}
if (-not $Env:GH_TOKEN -and $Env:GITHUB_TOKEN) {
	$Env:GH_TOKEN = $Env:GITHUB_TOKEN
}

. $PWSconfDir\env-vars.ps1		-WarningAction SilentlyContinue
. $PWSconfDir\env-check.ps1		-WarningAction SilentlyContinue
. $PWSconfDir\plugins.ps1		-WarningAction SilentlyContinue
. $PWSconfDir\aliases.ps1		-WarningAction SilentlyContinue
. $PWSconfDir\hotkeys.ps1		-WarningAction SilentlyContinue
. $PWSconfDir\.inc\kubectl-autocomplete.ps1 -WarningAction SilentlyContinue
. $PWSconfDir\wsl.ps1

#Attempting to load extras
if (Test-Path "${PWSconfDir}\extras.ps1" -PathType Leaf) { . "${PWSconfDir}\extras.ps1" }

# Chocolatey profile
$ChocolateyProfile = "$Env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) { Import-Module "$ChocolateyProfile" }

# Environment Checks
if ($RunEnvCheck) { . ${PSScriptRoot}\env-check.ps1 }

# Set keyboard prefs
# if ($IsWindows) { &Set-MyPrefsWinKeyboard }

#if ($IsWindows) { if ( Test-CommandExists winfetch ) { &winfetch } }
