# personal profile

# Ensure Homebrew commands are available in non-interactive login shells too.
[ -f "/home/linuxbrew/.linuxbrew/bin/brew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
DOTFILES_RUNTIME_ENV_FILE="${DOTFILES_RUNTIME_ENV_FILE:-$HOME/.config/dotfiles/runtime.env}"
[ -f "$DOTFILES_RUNTIME_ENV_FILE" ] && . "$DOTFILES_RUNTIME_ENV_FILE"

_dotfiles_load_runtime_env() {
  # Fallback for legacy setups that persisted SOPS key in ~/.profile.
  if [ -z "${SOPS_AGE_KEY:-}" ] && [ -f "$HOME/.profile" ]; then
    _dotfiles_sops_key="$(awk -F'\"' '/^export SOPS_AGE_KEY=/{print $2}' "$HOME/.profile" | tail -n1 | tr -d '\r')"
    [ -n "$_dotfiles_sops_key" ] && export SOPS_AGE_KEY="$_dotfiles_sops_key"
  fi
  if [ -z "${SOPS_AGE_KEY_FILE:-}" ] && [ -f "$HOME/.profile" ]; then
    _dotfiles_sops_key_file="$(awk -F'\"' '/^export SOPS_AGE_KEY_FILE=/{print $2}' "$HOME/.profile" | tail -n1 | tr -d '\r')"
    [ -n "$_dotfiles_sops_key_file" ] && export SOPS_AGE_KEY_FILE="$_dotfiles_sops_key_file"
  fi

  # Preferred path: encrypted runtime env generated by bootstrap.
  if [ -f "$HOME/.env.local.sops" ] && command -v sops >/dev/null 2>&1; then
    _dotfiles_env_tmp="$(mktemp)" || return
    if sops -d "$HOME/.env.local.sops" > "$_dotfiles_env_tmp" 2>/dev/null; then
      set -a
      # shellcheck disable=SC1090
      . "$_dotfiles_env_tmp"
      set +a
    fi
    rm -f "$_dotfiles_env_tmp"
  elif [ -f "$HOME/.env.local" ]; then
    # Legacy fallback for previous bootstrap versions.
    # shellcheck disable=SC1090
    . "$HOME/.env.local"
  fi

  [ -z "${GH_TOKEN:-}" ] && [ -n "${GITHUB_TOKEN:-}" ] && export GH_TOKEN="$GITHUB_TOKEN"
  [ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] && export OP_SERVICE_ACCOUNT_TOKEN="$(printf '%s' "$OP_SERVICE_ACCOUNT_TOKEN" | tr -d '\r')"
  [ -n "${GH_TOKEN:-}" ] && export GH_TOKEN="$(printf '%s' "$GH_TOKEN" | tr -d '\r')"
  [ -n "${GITHUB_TOKEN:-}" ] && export GITHUB_TOKEN="$(printf '%s' "$GITHUB_TOKEN" | tr -d '\r')"
  [ -n "${SOPS_AGE_KEY:-}" ] && export SOPS_AGE_KEY="$(printf '%s' "$SOPS_AGE_KEY" | tr -d '\r')"
  [ -n "${SOPS_AGE_KEY_FILE:-}" ] && export SOPS_AGE_KEY_FILE="$(printf '%s' "$SOPS_AGE_KEY_FILE" | tr -d '\r')"
}

_dotfiles_load_runtime_env
export DOTFILES_RUNTIME_ENV_LOADED=1

# Keep a stable signer command name in WSL/Linux.
# The generated wrapper fails fast when the 1Password SSH agent socket is
# unavailable, preventing git from hanging indefinitely during signed commits.
_dotfiles_ensure_op_ssh_sign() {
  if ! command -v op-ssh-sign-wsl.exe >/dev/null 2>&1; then
    return
  fi

  mkdir -p "$HOME/.local/bin"
  cat > "$HOME/.local/bin/op-ssh-sign" <<'WRAPPER'
#!/usr/bin/env bash
# Delegates to op-ssh-sign-wsl.exe.
# Checks for /tmp/1password-agent.sock or an existing SSH_AUTH_SOCK.
if [ -S /tmp/1password-agent.sock ]; then
  export SSH_AUTH_SOCK=/tmp/1password-agent.sock
elif [ -z "$SSH_AUTH_SOCK" ] || [ ! -S "$SSH_AUTH_SOCK" ]; then
  printf 'op-ssh-sign: No valid SSH agent socket found.\n' >&2
  exit 1
fi
exec op-ssh-sign-wsl.exe "$@"
WRAPPER
  chmod 700 "$HOME/.local/bin/op-ssh-sign"
}

# Bridge 1Password SSH Agent from Windows to WSL if not in VS Code and dependencies exist.
_dotfiles_bridge_1password_ssh() {
  local socket="/tmp/1password-agent.sock"
  # If inside VS Code, their native forwarding usually handles SSH_AUTH_SOCK.
  if [ -n "${VSCODE_IPC_HOOK_CLI:-}" ] && [ -S "${SSH_AUTH_SOCK:-}" ]; then
    return
  fi
  # If the socket already exists, use it.
  if [ -S "$socket" ]; then
    export SSH_AUTH_SOCK="$socket"
    return
  fi
  # Attempt to create the bridge if socat and npiperelay.exe are available.
  if command -v socat >/dev/null 2>&1 && command -v npiperelay.exe >/dev/null 2>&1; then
    rm -f "$socket"
    (setsid socat UNIX-LISTEN:"$socket",fork EXEC:"npiperelay.exe -ep -s //./pipe/openssh-ssh-agent",nofork &) >/dev/null 2>&1
    export SSH_AUTH_SOCK="$socket"
  fi
}
_dotfiles_bridge_1password_ssh

[ -n "$BASH" ] && [ -f ~/.bashrc ] && . ~/.bashrc

# uv
export PATH="$HOME/.local/bin:$PATH"

{ ble-edit/exec:gexec/.save-lastarg; } &>/dev/null
